"use client";

import { useMemo, useState } from "react";
import { ExternalLink, GitBranch, Globe, Lock, LogOut, RefreshCw, Search, ShieldCheck, Star } from "lucide-react";

type Repo={id:number;name:string;full_name:string;description:string|null;html_url:string;homepage?:string|null;updated_at:string;stargazers_count:number;private:boolean;visibility:string;website:string|null};

export default function AdminPage(){
 const [password,setPassword]=useState(""); const [authenticated,setAuthenticated]=useState(false);
 const [repos,setRepos]=useState<Repo[]>([]); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function login(){
  setLoading(true);setError("");
  try{const r=await fetch("/api/admin/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Login gagal");setRepos(d.repos||[]);setAuthenticated(true);setPassword("");}
  catch(e){setError(e instanceof Error?e.message:"Login gagal")}finally{setLoading(false)}
 }
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return !q?repos:repos.filter(r=>[r.name,r.full_name,r.description||"",r.visibility].join(" ").toLowerCase().includes(q))},[repos,query]);
 if(!authenticated)return <main className="adminLogin"><div className="adminLoginCard"><div className="adminShield"><ShieldCheck size={28}/></div><div className="eyebrow">ADMIN AREA</div><h1>Panel Admin</h1><p>Masuk untuk melihat seluruh repository GitHub, termasuk repository private.</p><form onSubmit={e=>{e.preventDefault();void login()}}><label>Password admin</label><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Masukkan password"/>{error&&<div className="adminError">{error}</div>}<button className="primary adminSubmit" disabled={loading||!password} type="submit"><ShieldCheck size={17}/>{loading?"Memeriksa...":"Masuk ke Admin"}</button></form><a className="backHome" href="/">Kembali ke dashboard</a></div></main>;
 const privateCount=repos.filter(r=>r.private).length,publicCount=repos.length-privateCount;
 return <main className="adminPage"><header className="adminTopbar"><div className="brand"><div className="logo"><ShieldCheck size={21}/></div><div><b>Vercel List Admin</b><span>Semua repository GitHub</span></div></div><button className="secondary" onClick={()=>{setAuthenticated(false);setRepos([])}} type="button"><LogOut size={16}/> Keluar</button></header><section className="adminContent"><div className="adminHeading"><div><div className="eyebrow">ADMIN DASHBOARD</div><h1>Semua project</h1><p>Repository public dan private yang dapat diakses token GitHub.</p></div><button className="refresh" onClick={()=>{setAuthenticated(false);setPassword("");}} type="button"><RefreshCw size={16}/> Sinkronkan</button></div><div className="adminStats"><div><GitBranch/><strong>{repos.length}</strong><span>Total project</span></div><div><Globe/><strong>{publicCount}</strong><span>Public</span></div><div><Lock/><strong>{privateCount}</strong><span>Private</span></div><div><Star/><strong>{repos.reduce((a,r)=>a+r.stargazers_count,0)}</strong><span>Total rating</span></div></div><div className="toolbar"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari semua project..."/></div></div><div className="adminGrid">{filtered.map(r=><article className="adminCard" key={r.id}><div className="adminCardTop"><div className="repoIcon"><GitBranch/></div><div className="cardTitle"><h3>{r.name}</h3><span>{r.full_name}</span></div><span className={r.private?"visibility private":"visibility public"}>{r.private?<Lock size={12}/>:<Globe size={12}/>} {r.visibility}</span></div><p>{r.description||"Tidak ada deskripsi repository."}</p><div className="meta"><span><Star size={14}/>{r.stargazers_count}</span><span>{new Date(r.updated_at).toLocaleDateString("id-ID")}</span></div><div className="cardBtns"><a href={r.html_url} target="_blank" rel="noreferrer"><GitBranch size={15}/> Repository</a>{r.website?<a className="liveBtn" href={r.website} target="_blank" rel="noreferrer"><Globe size={15}/> Website</a>:<span className="disabled"><Globe size={15}/> Belum ada website</span>}</div></article>)}</div>{filtered.length===0&&<div className="empty"><GitBranch size={35}/><h3>Project tidak ditemukan</h3></div>}</section></main>
}